.pylintrc
Makefile
craft_cli/messages.py
pyproject.toml
setup.cfg
setup.py
tests/unit/test_messages_emitter.py
tests/unit/test_messages_integration.py
tests/unit/test_messages_printer.py
tests/unit/test_stub.py

Introducing Emitter and _Printer (minimum usable code to bootstrap the project (CRAFT-95).

---

craft_cli/messages.py
tests/unit/test_messages_emitter.py
tests/unit/test_messages_printer.py

Added logging capabilities to the _Printer.

---

craft_cli/messages.py
tests/unit/test_messages_emitter.py
tests/unit/test_messages_integration.py
tests/unit/test_messages_printer.py

Added the 'progress' method to send progress messages (CRAFT-98).

---

craft_cli/messages.py
tests/unit/test_messages_emitter.py
tests/unit/test_messages_helpers.py
tests/unit/test_messages_integration.py
tests/unit/test_messages_printer.py

Added the API and infrastructure to show a progress bar (CRAFT-99).

---

craft_cli/messages.py
tests/unit/test_messages_helpers.py
tests/unit/test_messages_printer.py

Added a supervisor to show a spinner and passed time in a long-standing message (CRAFT-100).

---

craft_cli/messages.py
tests/unit/test_messages_helpers.py

Create the parent dirs if needed for the log file.

---

craft_cli/messages.py
tests/conftest.py
tests/unit/test_messages_emitter.py
tests/unit/test_messages_printer.py

The generalized fixture will be used in other test file in the next branch.

Improved a guard test (fixed the code) and generalized a fixture.

---

craft_cli/messages.py
tests/unit/test_messages_emitter.py
tests/unit/test_messages_integration.py

-----
This is because they are not intended to be part of the public API.

Made all the Emitter attributes private

---

craft_cli/messages.py
tests/unit/test_messages_emitter.py
tests/unit/test_messages_helpers.py
tests/unit/test_messages_integration.py

Get everything that is sent to logging system and show/log it (CRAFT-557).

---

setup.cfg

Added pywin32 only for windows in setup.cfg

---

craft_cli/messages.py

- [x Have you signed the [CLA](http://www.ubuntu.com/legal/contributors/)?
-----

Added info on how to use Emitter methods.

---

.pylintrc
Makefile
craft_cli/__init__.py
craft_cli/dispatcher.py
craft_cli/errors.py
craft_cli/helptexts.py
craft_cli/messages.py
tests/conftest.py
tests/factory.py
tests/unit/test_dispatcher.py
tests/unit/test_errors.py
tests/unit/test_help.py

New functionality from charmcraft (CRAFT-706).

---

.readthedocs.yml
docs/requirements.txt

Fixes #50
Signed-off-by: Sergio Schvezov <sergio.schvezov@canonical.com>
-----

docs: update readthedocs recipe

---

README.md
tests/unit/test_dispatcher.py

Also improved a detail in a test because newer pylint complains.

Include a section in README about setting up developer environment.

---

HOWTO_RELEASE.md
MANIFEST.in
craft_cli/__init__.py
examples.py
setup.cfg

Including several files and changes to make releases work.

Release 0.1.

---

craft_cli/dispatcher.py
tests/unit/test_help.py

The 'no such command' error now suggest similar commands (CRAFT-715).

---

craft_cli/dispatcher.py
docs/howtos.rst
tests/unit/test_dispatcher.py

Support for a default command in Dispatcher (CRAFT-760).

---

craft_cli/__init__.py

Release 0.2 (CRAFT-761)

---

examples.py

I broke this when doing tests for first release.

Restore old examples functionality.

---

craft_cli/__init__.py

Release 0.3.0

---

craft_cli/__init__.py

Release 0.5

---

craft_cli/messages.py
docs/explanations.rst
docs/tutorials.rst
examples.py
tests/unit/test_dispatcher.py
tests/unit/test_messages_emitter.py
tests/unit/test_messages_helpers.py
tests/unit/test_messages_integration.py

This is a very "mechanical branch", just name changes, no semantic ones.

Changed NORMAL to BRIEF and added a DEBUG verbosity level (still not used) (CRAFT-1134)

---

craft_cli/helptexts.py
tests/unit/test_help.py

This is an isolated helper still not used, in preparation for the next
branch of "help in markdown format".

Helper function to process commands overviews and leave markdown text.

---

examples.py

Not necessary, as I am an employee of Canonical.
-----

Update docstring to match updated code

---

docs/tutorials.rst

Found via `codespell .`.
-----

Fix typos and markdowns

---

docs/howtos.rst

docs: update wording in howtos.rst

---

.github/workflows/tests.yaml

-----
Linting issue is solved in #142, which is blocked by this one due to CI issues. We'll need to bypass checks on one of these.
Along with merging this PR we need to change the required checks to remove Ubuntu-18.04 tests.

ci: update CI platforms

---

.github/renovate.json5

ci: fix renovate schedule

---

pyproject.toml

chore(lint): add new typing dependencies and fix pyright issues

---

craft_cli/dispatcher.py
tests/unit/test_dispatcher.py

feat: expose the Dispatcher's parsed arguments

---

tests/test_pytest_plugin.py

style: fix typo in comment

---

craft_cli/printer.py
examples.py
tests/unit/test_printer.py

fix: make repeated text keep the spinner

---

pyproject.toml

These ignores were supposed to be recursive. Ope

style: fix pyright config

---

.github/workflows/tests.yaml
pyproject.toml
tox.ini

chore: switch to ruff snap

---

craft_cli/errors.py
craft_cli/messages.py
docs/.custom_wordlist.txt
docs/changelog.rst
docs/index.rst
tests/unit/test_messages_emitter.py

The latest commit is new: it adds a missing changelog, with entries for 2.6.0

Merge `rockcraft` back into `main`

---

.github/renovate.json5
.github/workflows/check-renovate.yaml

https://github.com/canonical/starbase/pull/232

ci: update renovate from starbase

---

docs/changelog.rst

docs: changelog entries for 2.7.0

---

craft_cli/helptexts.py
docs/tutorials.rst
tests/unit/test_help.py

feat: display positional args in help

---

.github/workflows/release-publish.yaml

ci: use Trusted Publishing for PyPI releases

---

craft_cli/dispatcher.py
docs/changelog.rst
tests/unit/test_help.py

fix: don't suggest hidden commands

---

craft_cli/helptexts.py
tests/unit/test_help.py

feat: remove code backticks in CLI help messages

---

docs/changelog.rst

docs: finalize changelog for 2.12.0

---

docs/changelog.rst

docs: finalize changelog for 2.14.0

---

docs/changelog.rst

docs: finalize changelog for 2.15.0

---

craft_cli/dispatcher.py

https://canonical-craft-cli--327.com.readthedocs.build/en/327/craft_cli/#craft_cli.Dispatcher

style(docstring): improve the output of a docstring in Sphinx

---

docs/.wordlist.txt
docs/how-to-guides/index.rst
docs/how-to-guides/use-completion.rst
docs/how-to-guides/use-the-completion-module.rst

----
To help a bit with the review of accuracy, here's me using the module in Snapcraft.
- `get_app_info()`: https://github.com/canonical/snapcraft/blob/7254a4bd5a9f4b5a22c979c9b86fa364f2232fcf/snapcraft/application.py#L475
- Invoking it during build: https://github.com/canonical/snapcraft/blob/7254a4bd5a9f4b5a22c979c9b86fa364f2232fcf/snap/snapcraft.yaml#L217

docs: document how to use the completion module

---

docs/changelog.rst

docs: finalize changelog for 3.0.0

---

.github/workflows/tests.yaml

ci: replace focal with noble

---

.github/workflows/tics.yaml

---
Sets the Tiobe project name and specifies another branch for workflow testing.

ci: set tiobe project name

---

.pre-commit-config.yaml
craft_cli/dispatcher.py
craft_cli/messages.py
craft_cli/pytest_plugin.py
pyproject.toml
tests/integration/test_messages_integration.py
tests/unit/test_messages_helpers.py

---
Fixes some new lint errors that came in from Ruff 0.12.

style: fix lints from ruff 0.12

---

docs/changelog.rst

---
Finalizes the changelog for a 3.1.0 release.

docs: finalize 3.1.0

---

.github/workflows/release-publish.yaml
craft_cli/messages.py
craft_cli/pytest_plugin.py
examples.py
tests/integration/test_messages_integration.py
tests/test_pytest_plugin.py
tests/unit/test_messages_emitter.py

---
Adds a warning method to the Emitter class.
Resolves #256.

feat(emitter): add warning method
