canonical/craft-cli

- craft_cli/messages.py
- tests/unit/test_messages_emitter.py
- tests/unit/test_messages_integration.py
Specifically:
- receive and pass the application name when getting the log file path
- call .show to log the greeting in the file one moment after creating it (with stream=None, for it to not to be shown to the screen)
- show the log filepath to the screen the moment the mode is set to verbose or trace
Note that all the "integration" tests were modified to also verify what was actually sent to the file.
-----
> Use all log-related functionality from the Emitter.

- Makefile
- craft_cli/messages.py
- tests/unit/test_messages_emitter.py
- tests/unit/test_messages_integration.py
> Added a .trace method to Emitter to show trace information (CRAFT-97).

- craft_cli/messages.py
- tests/unit/test_messages_helpers.py
-----
This can easily be experimented in real life before/after the change doing `./examples.py 18`.
> Avoid showing the spinner on complete line messages (that end with newline).

- Makefile
- docs/conf.py
- docs/index.rst
Read The Docs can build the API documentation (reference) by moving
sphinx-apidoc to conf.py which is its entry point for building.
Some typos were also corrected.
Signed-off-by: Sergio Schvezov <sergio.schvezov@canonical.com>
-------
-----
> docs: move API gen to conf.py for RTD to pick up

- craft_cli/errors.py
- craft_cli/messages.py
`mypy --strict` enforces these by default.
I'm not sure whether `Emitter` should be public.  It doesn't have an underscore, but it also isn't used by charmcraft - I guess it might be needed to implement test fixtures?  I decided to err on the side of strictness and you can always open it up if you want.
-----
> Declare public API names

- craft_cli/errors.py
- tests/unit/test_errors.py
This is especially helpful for testing purposes so that the actual instance
of CraftError can be compared with the expected one.
This fixes #40
(not necessary -> Canonical employee)
-----
> Implement comparison for CraftError

- tox.ini
The requirements files were removed a while ago, but `tox.ini` still
referenced them.
> Fix tox environment setup

- craft_cli/__init__.py
Explicitly export public API names. This is enforced by pyright in
packages with the PEP-561 `py.typed` marker.
Signed-off-by: Claudio Matsuoka <claudio.matsuoka@canonical.com>
-----
> api: declare public api names

- craft_cli/messages.py
- tests/unit/test_messages_printer.py
If the output stream isn't a terminal (for example, if *craft is running
in a Launchpad build job), then showing spinners isn't very useful and
results in build logs parts of which are quite hard to read.  Limit this
behaviour to terminals.
> Only show spinners if the stream is a terminal

- craft_cli/messages.py
- docs/howtos.rst
- examples.py
- tests/unit/test_messages_emitter.py
While paused, the Emitter frees completely the terminal and does not do anything with it. Not even getting logs from it.
Examples 21 and 22 added to easily test this new feature.
> Add a 'pause' method to the Emitter (CRAFT-907).

- craft_cli/messages.py
- examples.py
- tests/unit/test_messages_emitter.py
- tests/unit/test_messages_printer.py
- the _Printer now opens the log in "append" mode; this is particularly so after resuming the previous log is not truncated, but also is an improvement in general, as we allow users of the library to have better control if they provide the log filepath (if they want a fresh start, they can truncate it, before we were not leaving a choice)
- ensure the _Emitter is not used when paused... but I fixed this in a more generic way, ensuring that the _Emitter is not used when stopped! Except for the `ended_ok` and `error` methods, where we provide the possibility of double-endings (ignoring the call), to support race conditions when closing the lib.
> Improvements/fixes for the pause situation.

- craft_cli/pytest_plugin.py
- docs/howtos.rst
- setup.cfg
- tests/conftest.py
- tests/test_pytest_plugin.py
- tests/unit/test_dispatcher.py
- tests/unit/test_help.py
- tests/unit/test_messages_emitter.py
- tests/unit/test_messages_printer.py
Both are brought from Charmcraft, but here are also tested (as they are not really *used*, but are provided for users of the library).
As these fixtures also work for the project itself (because for development the project itself is installed), I removed the redundant fixture in `conftest.py`. Related to this, instead of enabling that fixture in a couple of test files, in consideration that the "real" `init_emitter` fixture has `autouse=True`, I just turned it off where we didn't want to mess with tests.
Fixes #57.
> Added init_emitter and emitter fixtures (CRAFT-994).

- docs/explanations.rst
Added a startup code sequence proposal (docs/explanations.rst) for
supporting configurable Emitter verbosity levels during early module
initialization.
-----
> docs: add explanation for early emitter init usage

- craft_cli/messages.py
- examples.py
- tests/unit/test_messages_emitter.py
- tests/unit/test_messages_integration.py
Note that Emitter final behaviour (as described in the Spec) will only be achieved after more several PRs, I added XXX notes for changes that will happen in the short term future.
This branch is for sure the most "conceptual" one in the "verbosity levels" series. The changes in the code are not many, but the tests are seriously affected (and will continue to mutate when other PRs land). My recommendation is to analyze the changes in the code using [the Spec itself](https://docs.google.com/document/d/1pJDT-NE3jhkfVvDw6ba0Z3adnaQnGRi9slC9jIOqrZ4/edit) for better reasoning..
> Refactor Emitter to comply with the new verbosity levels behaviour (CRAFT-1136).

- craft_cli/messages.py
- examples.py
- tests/unit/test_messages_emitter.py
- tests/unit/test_messages_integration.py
These two behave ok according to the new Spec.
Also I moved the "pause started" and "pause ended" to be signaled using
internal .debug (now that it's available) as before they will only
appear in the logs if TRACE mode.
> Added the .debug and .verbose methods to Emitter (CRAFT-1137).

- craft_cli/messages.py
- tests/unit/test_messages_emitter.py
- tests/unit/test_messages_helpers.py
- tests/unit/test_messages_integration.py
- tests/unit/test_messages_printer.py
Details:
- it shows messages with timestamps when needed
- it marks the beginning and end of the progress in general (very useful for example for logs, where the *progress itself* is not recorded)
- as that context info is responsibility of the class itself, there is no more a separate message before putting it to work.
Also added support in the Printer to show the timestamp for the progress bar, if indicated.
> Improved the _Progresser and how it's used (CRAFT-1139).

- craft_cli/messages.py
- tests/unit/test_messages_helpers.py
> Support the unlinking of files that were just removed in the logpath helper (CRAFT-1125).

- Makefile
- craft_cli/messages.py
- tests/unit/test_messages_printer.py
The fix can be tested IRL by using `expect` with the following script:
```
set stty_init "rows 100 cols 0"
spawn env/bin/python examples.py 1
expect "The meaning of life is 42."
```
> Behave as 'captured output' when the (fake) terminal has zero columns (CRAFT-1128).

- craft_cli/messages.py
This patch ensures that there is no risk of reaching FD_SETSIZE
in a pipe FD. That would prevent select to run and would return
an error:
ValueError: filedescriptor out of range in select()
This patch is complementary to
https://github.com/canonical/craft-cli/pull/103
and both should be applied to fully fix the bug.
Fix https://github.com/canonical/craft-cli/issues/102
-----
> Use poll instead of select

- craft_cli/messages.py
- tests/unit/test_messages_stream_cm.py
The _PipeReaderThread() class creates two pipes to manage input/output, and uses SELECT() to know when there is data to be read. Unfortunately, those two pipes aren't closed when the thread ends, which means that the FDs of the pipes of new classes will grow up and up. The problem is that SELECT has a limit in the FD value that can monitor, usually 1024, which means that any FD with a value greater than that can't be monitored by it, and will show the error if tried to:
`  ValueError: filedescriptor out of range in select()`
With small snaps this is not a problem because they don't create so many objects of this kind as to reach the limit, but with very big snaps (like Gnome-42-2204-SDK, with more than 50 binaries), it can be achieved.
This MR partially fixes this by closing the FDs when …
> Close pipes when the thread ends

- craft_cli/dispatcher.py
- tests/unit/test_dispatcher.py
As part of the "help with markdown output" work I needed to generalize the custom argument parsing, and found that we were raising errors without the proper "usage format" in a couple of cases. Fixed that.
> Generalized the custom argument parsing, and fixed two exceptions in the process

- craft_cli/dispatcher.py
- tests/unit/test_help.py
In preparaion to the "help with markdown output" work I better tested the help parsing function, and fixed a bug where the error was not properly raises when `--all` was used with some extra info.
> Better tested help parsing function, with a bug fixed.

- craft_cli/dispatcher.py
The returned exception is always raised where the function is called.
> Return the exception, not raise it.

- craft_cli/messages.py
- examples.py
- setup.cfg
- tests/unit/test_messages_integration.py
- tests/unit/test_messages_printer.py
It is a very common pattern for craft tools to start the session
directly on a host machine, but launch another craft instance to
do the actual work inside LXD or Multipass.
In order for a seamless CLI experience (which looks identical
between a 'destructive build' on the host, LXD or Multipass),
we need support for progress messages (ephemeral=True) to seamlessly
cross the boundaries between the host and the container instance of
of the craft tool.
Please see examples.py #26 for an example.
Add support for _Printer to respect ephemeral messages when
stopping. On printer stop(), these messages are no longer terminated
with a newline, but instead the printer will clear and reset the
cursor to the start of the line.
This behaviour change will allow subsequent terminal writes by a
different …
> printer: enhance ephemeral message handover after stop() or pause()

- craft_cli/messages.py
- docs/explanations.rst
- examples.py
- tests/unit/test_messages_emitter.py
- tests/unit/test_messages_integration.py
- tests/unit/test_messages_stream_cm.py
Also added an example to show this (and improved the whole examples machinery to accept parameters, to make it easier to use).
Added a couple of small changes because pyright/pylint, and will split the big `messages.py` in a following branch (without semantic changes in it).
Documentation updated.
No change needed from the applications using the library.
> (messages) Show messages from subprocess in an ephemeral way when in brief mode. (CRAFT-1542)

- setup.cfg
See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-license-file
Committed via https://github.com/asottile/all-repos
> packaging: replace deprecated setuptools directive

- craft_cli/messages.py
I'm not sure if this is the best solution here or we should use something like `printer.start` / `printer.recreate`.
I also think some unit tests would be nice and will add them if this solution is approved.
fixes: #139
> fix new printer for logging handler

- craft_cli/messages.py
- examples.py
- tests/unit/test_messages_stream_cm.py
The tabs complicate the internal book-keeping because "\t12" has 3 characters but is printed to the terminal with a varying number of spaces (depending on the user's tabwidth). For the pipe reader used in open_stream(), this issue manifested as a bug where lines containing tabs would result in multiple lines being printed (instead of just the last one), which breaks the "ephemeral" aspect of the stream.
Note that this discovery implies that we should probably revisit this tab issue in more places; in particular, the Printer does multiple comparisons between the len() of the text and the terminal width, so if the text has tabs that comparison will be incorrect. However, this commit aims only to fix the (unreleased) behavior of showing subprocess output as ephemeral messages inside …
> messages: replace tabs with spaces in open_stream()

- pyproject.toml
- tox.ini
The problem: when using pytest-cov to integrate coverage with the test
run, there is a 'race' between pytest-cov and the pytest plugin provided
by craft-cli (the emitter). When craft-cli's plugin is loaded first, it
necessitates importing the main 'craft_cli' package, which in turn
imports dispatcher.py, messages.py, etc.
As a result, all the top-level lines (class and function definitions,
global-variables, etc) are loaded _before_ coverage starts running,
meaning that they are marked as 'hits' because they are never "loaded
again" during the tests. Instead, use coverage specifically so that
it's always set-up before the whole importing starts.
> tools: call 'coverage' directly

- craft_cli/dispatcher.py
List is invariant, whereas sequence is covariant. Since CommandGroup always wants subclasses, we should use Sequence
> type: change CommandGroup.commands from List to Sequence

- craft_cli/__init__.py
- craft_cli/dispatcher.py
- craft_cli/errors.py
- craft_cli/messages.py
- docs/conf.py
Instead of keeping their docs in the main class docstring, use per- attribute docstrings to improve the readibility and "searchability" of the items. Some minor tweaks and adjustments to the text itself, but nothing too major.
Note that we also drop the "sphinx.ext.more_autodoc" extension because it isn't adding anything (that I can tell) other than an annoying double list of init parameters that I couldn't get rid of.
CRAFT-1180
> docs: document class attributes separately

- craft_cli/messages.py
- craft_cli/printer.py
- examples.py
- tests/unit/test_messages_helpers.py
- tests/unit/test_messages_integration.py
This commit adds a new feature to the Emitter, tentatively called "streaming brief". It is initially disabled, and can be enabled in the Emitter's init() call.
Once enabled, the feature will leverage the "multi-action" nature of progress() calls to "stream", in a single line, info-level log messages and text written to the open_stream()'s pipe. For example, the following sequence of calls in BRIEF mode:
```
emit.progress("Starting stage 1", permanent=False) ...
log.info("Doing first step")
...
log.info("Doing second step")
...
emit.progress("Finished stage 1", permanent=True)
```
... will cause the two 'info' messages to "stream" on the terminal, prefixed by "Starting stage 1 ::" to indicate that they are related to that progress message. All these three messages are ephemeral which means …
> emitter: add "streaming brief" feature

- craft_cli/messages.py
- tests/integration/test_messages_integration.py
- tests/unit/test_messages_emitter.py
> feat(emit): make text param in open_stream() optional

- craft_cli/dispatcher.py
- craft_cli/helptexts.py
- tests/unit/test_help.py
> feat: allow the application to choose the help order of commands

- docs/custom_conf.py
Upstream workflow has been bumped to use Python 3.10, so we can remove our bespoke initialisation of "every sphinx-toolbox extension except autonamedtuple".
> chore: re-enable sphinx-toolbox

- craft_cli/messages.py
- craft_cli/printer.py
- tests/integration/test_messages_integration.py
The first commit fixes a bug I bumped into where an `emit.progress()` followed by an `emit.message()` would send the carriage return (to clear the ephemeral progress) to the wrong stream. The second commit then does the actual clearing of the prefix.
Fixes #202
> fix: clear prefix for message() and error()

- docs/.sphinx/requirements.txt
- docs/custom_conf.py
- pyproject.toml
We don't use the library at all - probably what happened is that we copied the deps from somewhere else.
Fixes #201
> chore(deps): drop Pydantic dependency

- craft_cli/messages.py
- tests/unit/test_messages_stream_cm.py
Since these bytes come from the output of unknown processes, there is no guarantee that they are valid utf-8 text. We also have no way to know what encoding they have (if any), so the best we can do is replace the invalid bytes with the usual unicode marker for that.
Fixes #221
> fix: handle errors when decoding bytes from subprocesses

- craft_cli/dispatcher.py
- pyproject.toml
In these cases, the chaining doesn't provide useful additional data.
Drive-by: updates ruff to 0.2
> fix(dispatcher): explicitly disable exception chaining

- craft_cli/errors.py
- craft_cli/messages.py
- tests/unit/test_messages_emitter.py
This commit provides a way to separate the base url for the project's docs and the slug for a specific topic. In particular, this is useful when raising a CraftError so that it holds just the slug of the user documentation for that issue, which is then combined by the Emitter into a full url when reporting the error to the user.
> feat: split the docs url into base and slug

- .github/workflows/release-publish.yaml
This workflow file is a copy of Starbase's, with the modification to run on self-hosted runners (and to use Python 3.10 instead of 3.11).
> ci: add workflow to release to PyPI

- craft_cli/__init__.py
- craft_cli/dispatcher.py
- craft_cli/errors.py
- craft_cli/messages.py
- craft_cli/printer.py
- tests/unit/test_errors.py
- tests/unit/test_messages_emitter.py
This new error class has a ``stderr`` attribute that holds the error output of an executed command. As the class' docstring indicates, this new attribute is halfway between ``brief`` and ``details``, verbosity-wise. It's meant to be used in cases where this error output is expected to be useful enough to the end user to make up for the extra text, even in "brief"-mode executions.
Fixes #260
> feat: add CraftCommandError

- craft_cli/messages.py
- examples.py
- tests/integration/test_messages_integration.py
The bug manifested in a situation like this:
- A long progress() message is printed, say "AAAAAAAA";
- An error is emitter, and the result of str(error) is a multi-line string where the first line is shorter than the previously-emitted progress() message. Example: "BBBB\nCCCC";
- The newline in the error message is not correctly handled by the printer, meaning that after "BBBB" is written to the terminal the remainder of the line is not cleared. So the end result looks like:
> BBBBAAAA
> CCCC
The "proper" fix for this would mean a big rework on the printer to properly support multi-line messages; for now, fix only the error case by "manually" splitting the error message and printing each line individually.
Fixes #263
> fix: correctly print multi-line errors

- craft_cli/dispatcher.py
- docs/changelog.rst
- tests/unit/test_help.py
This lets the commands of a given application access the configuration dict during fill_parser() even when building the help message, like in `app cmd -h`. Of course, this can only be used in cases where the configuration dict contains data that the application already has at pre_parse_args()-time.
Fixes #292
> feat: support app_config in pre_parse_args()

- .github/workflows/release-publish.yaml
We can't enable Trusted Publishing yet because I need to be able to update the PyPI project first.
> chore(ci): generate notes when publishing a release

- craft_cli/dispatcher.py
- craft_cli/helptexts.py
- docs/changelog.rst
- tests/unit/test_dispatcher.py
- tests/unit/test_help.py
Adds a documentation link to the bottom of general help and a command-specific link to command help messages.
I did not add a URL link to the markdown format of command help.
> feat: add documentation link in help messages

- craft_cli/messages.py
- docs/changelog.rst
- tests/unit/test_messages_emitter.py
With this fix, ``Emitter.set_mode(mode)`` becomes a no-op if the emitter is already at that ``mode``. This scenario can happen, for example, if the Emitter is initialized with a mode and then the Dispatcher sets the same mode during command-line handling.
> fix: only greet once when setting the same mode

- craft_cli/pytest_plugin.py
- tests/test_pytest_plugin.py
> feat(pytest): add an assert_error plugin method

- craft_cli/messages.py
- pyproject.toml
- tox.ini
The version of black was not supported with Python 3.8, the alternative was to switch to the snap version of black.
The commit affecting pyproject.toml and tox.ini is transposed from https://github.com/canonical/charmcraft/commit/d2b40dfbece3e9cc8577c19407c2dedbc30e9d2f and https://github.com/canonical/charmcraft/commit/9583793226b73478b9af24d649f0c1ca2b83c9bb with the exception of the ISC ignore in pyproject.toml
The second commit is a result of the ruff formatting
> Remove black

- craft_cli/messages.py
- docs/changelog.rst
- tests/conftest.py
- tests/unit/test_messages_emitter.py
This adds a confirm method to the emitter, allowing the program to ask the user a yes/no question.
Fixes #130
> feat: confirm method for the emitter

- craft_cli/pytest_plugin.py
- docs/changelog.rst
- tests/test_pytest_plugin.py
Reverts canonical/craft-cli#218
Breaks #162 
Confirmed this is the cause. Compare:
- With #218: https://github.com/canonical/craft-application/actions/runs/12305359436/job/34344765176?pr=586
- Without: https://github.com/canonical/craft-application/actions/runs/12305776816/job/34346114053?pr=594
> fix(pytest): revert "add an assert_error plugin method"

- craft_cli/messages.py
- docs/changelog.rst
- tests/integration/test_messages_integration.py
- tests/unit/test_messages_emitter.py
Produces:
The extra Craft Parts message to be removed in Craft Parts
> feat: enable details except in quiet

- .github/workflows/release-publish.yaml
- docs/changelog.rst
Also manually-cherry-pick a starbase commit to constrain wheel uploads to `amd64`
> docs: finalize 2.13.0 changelog

- .github/workflows/tests.yaml
- tox.ini
Run tests in CI on Python `3.12` instead of `3.11`
> ci(test): run on 3.12 instead of 3.11

- .pre-commit-config.yaml
- craft_cli/messages.py
- docs/changelog.rst
- tests/unit/test_messages_emitter.py
Add a functionality to prompt user for an input.
Additionally with `hide` set to `True` user may be asked for a secret input.
(CRAFT-3739)
> feat: add prompt to emitter

- craft_cli/dispatcher.py
- craft_cli/helptexts.py
- pyproject.toml
Two of the referenced linter rules in pyproject were unsupported by the schema. This PR removes them.
> chore: update ruff configuration for 0.8

- craft_cli/completion/completion.py
- tests/integration/test_completion.py
Fixes an issue when using the completion generator with craft tools based on craft-application.
CRAFT-3994
> fix(completion): use an app_config if present

- pyproject.toml
We don't actually use it for anything, and since we're prepping for a major release we might as well drop it.
> build(deps): drop pyyaml dependency

- craft_cli/messages.py
- docs/changelog.rst
- tests/integration/test_messages_integration.py
- tests/unit/test_messages_emitter.py
Adds a new function to dump external logs directly into the emitter's log file, bypassing printing to the terminal and giving better customization for log behavior in the future.
It additionally adds a public `log_filepath` read-only property so consumers of the emitter can more easily access and test the contents of the log.
Required by https://github.com/canonical/craft-application/pull/691.
> feat(emitter): add a log dumping function

- craft_cli/printer.py
- examples.py
This stops the printer when garbage collecting it, even if it hasn't been manually stopped. This stops the printer before exiting the process no matter what.
Fixes #334
> fix(printer): stop the printer on destruct

- craft_cli/messages.py
- examples.py
- tests/unit/test_messages_emitter.py
This makes an error's details a bit easier to visually identify, in the case of long multi-lined details.
---
> feat: prepend newlines to details if necessary

- craft_cli/dispatcher.py
- docs/changelog.rst
- tests/unit/test_dispatcher.py
---
Emits a warning when the default command is used. 
Snapcraft is the only *craft app affected by this.
Creates #361
Unblocks https://github.com/canonical/snapcraft/issues/5525
(SNAPCRAFT-1149)
> feat(dispatcher): add a warning for the default command

- craft_cli/dispatcher.py
- docs/changelog.rst
- tests/unit/test_dispatcher.py
---
I didn't notice the missing space, because I was testing in a narrow terminal.
> fix: correct typo in default command warning

- craft_cli/printer.py
- docs/changelog.rst
- tests/unit/test_printer.py
The errors happened because we now unconditionally stop() the Printer at process exit, but the stop() method was not conscious enough of the state of the things it was trying to stop - unfinished streams that might already be closed, spinner threads that were never started, etc.
Fixes #356 and #341
---
> fix: cleanup errors when stopping printer in tests

- craft_cli/completion/bash_completion.sh.j2
- craft_cli/completion/completion.py
- tests/integration/test_completion/expected_script.sh
---
The result of a lint workflow on one of our PR's ([here](https://github.com/canonical/craft-cli/actions/runs/16973778349/job/48117243596?pr=372#step:6:22)) revealed that one of the fields on the completion script wasn't actually being used or filled in as anything.
> chore: clean up an unused field from the completion script
